<a href="https://colab.research.google.com/github/eallan06/Exercicio-Pr-tico-7/blob/main/Exercicio_Pr%C3%A1tico_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

tabela = pd.read_csv("/content/drive/MyDrive/vendas_brasil_aula4_kpis.csv")
display(tabela)

,pedido_id,data_venda,uf,canal_venda,categoria,produto,quantidade_pedidos,preco_unitario,receita,lucro
0,5000,2025-02-14,RJ,Marketplace,Periféricos,Mouse Gamer,2,237.65,475.30,239.08
1,5001,2025-02-17,PR,Online,Informática,Monitor 27,4,1431.79,5727.16,1769.48
2,5002,2025-07-22,RJ,Marketplace,Informática,Monitor 27,5,1446.22,7231.10,2449.85
3,5003,2025-12-08,SP,Marketplace,Periféricos,Teclado Mecânico,7,399.84,2798.88,1356.67
4,5004,2025-01-04,GO,Marketplace,Telefonia,Smartphone X,4,3134.85,12539.40,3656.84
...,...,...,...,...,...,...,...,...,...,...
415,5415,2025-02-23,RJ,Marketplace,Informática,Notebook Pro,4,4238.28,16953.12,4730.36
416,5416,2025-12-03,PR,Loja Física,Periféricos,Teclado Mecânico,6,332.32,1993.92,786.18
417,5417,2025-04-28,RS,Online,Telefonia,Smartphone X,3,2717.23,8151.69,2209.32
418,5418,2025-06-07,RS,Online,Telefonia,Tablet Plus,3,2290.19,6870.57,2232.72
419,5419,2025-06-11,GO,Online,Informática,Notebook Pro,3,3939.12,11817.36,2539.26

In [4]:
import pandas as pd

# 1. Leitura e Preparação
df = pd.read_csv('vendas_brasil_aula4_kpis.csv')
df['data_venda'] = pd.to_datetime(df['data_venda'])

# 2. Cálculo dos KPIs Globais
receita_total = df['receita'].sum()
lucro_total = df['lucro'].sum()
margem_global = (lucro_total / receita_total) * 100
ticket_medio = receita_total / df['pedido_id'].nunique()

print(f"--- KPIs GLOBAIS ---")
print(f"Receita: R$ {receita_total:,.2f}")
print(f"Lucro: R$ {lucro_total:,.2f}")
print(f"Margem: {margem_global:.2f}%")
print(f"Ticket Médio: R$ {ticket_medio:,.2f}\n")

# 3. Análise por Canal (Dimensão)
analise_canal = df.groupby('canal_venda').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'pedido_id': 'nunique'
}).rename(columns={'pedido_id': 'qtd_pedidos'})

analise_canal['margem_%'] = (analise_canal['lucro'] / analise_canal['receita']) * 100
display(analise_canal.sort_values(by='margem_%', ascending=False))

--- KPIs GLOBAIS ---
Receita: R$ 1,921,492.22
Lucro: R$ 544,496.15
Margem: 28.34%
Ticket Médio: R$ 4,574.98

               receita      lucro  qtd_pedidos   margem_%
canal_venda
Online       622893.07  184110.42          136  29.557307
Marketplace  657802.09  185802.57          141  28.245968
Loja Física  640797.06  174583.16          143  27.244688